name 'freetds'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures freetds'
long_description 'Installs/Configures freetds'
version '0.1.0'
chef_version '>= 13.0'
# issues_url 'https://github.com/<insert_org_here>/freetds/issues'
# source_url 'https://github.com/<insert_org_here>/freetds'
depends 'tar'

